import React from "react";
import {
    IDialogContentProps,
    DialogType,
    IButtonStyles,
    Stack,
    StackItem,
    Label,
    PrimaryButton,
    DefaultButton,
    Dialog,
    DialogFooter,
    initializeIcons,
    ThemeProvider,
    createTheme,
    Theme,
    IPalette,
} from "@fluentui/react";
import { AsyncTrunk, parseStore } from "mobx-sync";
import { comparer, configure, reaction } from "mobx";
import { observer } from "mobx-react-lite";
import he from "he";

import * as CycleChooserController from "./CycleChooserController";
import * as PacketLoaderController from "./PacketLoaderController";
import * as TossupQuestionController from "./TossupQuestionController";
import { StateProvider } from "../contexts/StateContext";
import { IErratum } from "../state/IErratum";
import { TiebreakerContext, ITiebreakerContextValue, ITiebreakerItem } from "../contexts/TiebreakerContext";
import { BelowTossupContext } from "../contexts/BelowTossupContext";
import { NewGameNoticeContext, INewGameNoticeContextValue } from "../contexts/NewGameNoticeContext";
import { HostNewGameContext, IHostNewGameContextValue } from "../contexts/HostNewGameContext";
import * as QBJ from "../qbj/QBJ";
import { IMatch } from "../qbj/QBJ";
import { AppState } from "../state/AppState";
import { GameViewer } from "./GameViewer";
import { ModalDialogContainer } from "./ModalDialogContainer";
import { IGameFormat } from "../state/IGameFormat";
import { IPacket } from "../state/IPacket";
import { IPlayer, Player } from "../state/TeamState";
import { PendingGameType } from "../state/IPendingNewGame";
import { Bonus, PacketState, Tossup } from "../state/PacketState";
import { ICustomExport } from "../state/CustomExport";
import { IHostSettings } from "../state/IHostSettings";
import { Cycle } from "../state/Cycle";
import { UIState } from "../state/UIState";
import { ModalVisibilityStatus } from "../state/ModalVisibilityStatus";
import { IPacketParserLink } from "../state/UIState";
import {
    IHostNewGame,
    IHostTeam,
    ILiveTeam,
    startHostNewGame,
    syncLiveTeams,
} from "./HostGameController";

export type { IHostNewGame, IHostTeam, ILiveTeam };
import { IStatus } from "../IStatus";

// Initialize Fluent UI icons when this is loaded, before the first render
initializeIcons();

// We may want to make this customizable, but for now set it to 5 days
const minAgeToPromptForReset = 5 * 1000 * 60 * 60 * 24; // 5 days in ms

const lightModePalette: Partial<IPalette> = {
    themePrimary: "#0078d4",
    themeLighterAlt: "#eff6fc",
    themeLighter: "#deecf9",
    themeLight: "#c7e0f4",
    themeTertiary: "#71afe5",
    themeSecondary: "#2b88d8",
    themeDarkAlt: "#106ebe",
    themeDark: "#005a9e",
    themeDarker: "#004578",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralSecondaryAlt: "#8a8886",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
};

// Generated by going to https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html
// and using the inverse for each of the three main colors. This looks better than swapping black/white values for
// lightModePalette
const darkModePalette: Partial<IPalette> = {
    themePrimary: "#0078d4",
    themeLighterAlt: "#000508",
    themeLighter: "#001322",
    themeLight: "#00243f",
    themeTertiary: "#00487f",
    themeSecondary: "#006aba",
    themeDarkAlt: "#1684d8",
    themeDark: "#3595de",
    themeDarker: "#66afe7",
    neutralLighterAlt: "#0b0b0b",
    neutralLighter: "#151515",
    neutralLight: "#252525",
    neutralQuaternaryAlt: "#2f2f2f",
    neutralQuaternary: "#373737",
    neutralTertiaryAlt: "#595959",
    neutralTertiary: "#f3f3f3",
    neutralSecondary: "#f5f5f5",
    neutralSecondaryAlt: "#757779", // This is going to be the inverse of light's neutralSecondaryAlt, so there's some distinguishment between neutral secondary
    neutralPrimaryAlt: "#f7f7f7",
    neutralPrimary: "#eeeeee",
    neutralDark: "#fbfbfb",
    black: "#fdfdfd",
    white: "#000000",
};

export const ModaqControl = observer(function ModaqControl(props: IModaqControlProps): JSX.Element {
    const [appState]: [AppState, React.Dispatch<React.SetStateAction<AppState>>] = React.useState(() => new AppState());

    // Errata the host owns (e.g. loaded from its server): adopt them whenever
    // that reference changes. Starting a new game clears errata, since they
    // describe the packet that was just played, so re-seed the host's when that
    // happens -- they're the host's to keep, not the game's.
    const hostErrata: IErratum[] | undefined = props.errata;
    React.useEffect(() => {
        if (hostErrata == undefined) {
            return;
        }

        appState.errata.setErrata(hostErrata);
        return reaction(
            () => appState.game.isLoaded,
            (isLoaded) => {
                if (isLoaded && appState.errata.errata.length === 0) {
                    appState.errata.setErrata(hostErrata);
                }
            }
        );
    }, [appState, hostErrata]);

    // Hand the host every change the moderator makes, so it can save errata with
    // the tournament.
    const onErrataChange = props.onErrataChange;
    React.useEffect(() => {
        if (onErrataChange == undefined) {
            return;
        }

        return reaction(
            () => appState.errata.errata.map((erratum) => ({ ...erratum })),
            (errata) => onErrataChange(errata),
            // Otherwise adopting the host's own errata (above) would echo them right back at it
            { equals: comparer.structural }
        );
    }, [appState, onErrataChange]);

    // Tiebreakers: append the chosen question to the packet (so the next/thrown-
    // out tossup reads it) and report which teams heard it.
    const tiebreakers = props.tiebreakers;
    const onTiebreakerUsed = props.onTiebreakerUsed;
    const addTiebreaker = React.useCallback(
        (index: number): void => {
            const item = tiebreakers?.[index];
            if (item == undefined) {
                return;
            }
            const combined: PacketState = new PacketState();
            combined.setTossups(
                appState.game.packet.tossups.concat([new Tossup(he.decode(item.question), he.decode(item.answer))])
            );
            combined.setBonuses(appState.game.packet.bonuses);
            combined.setName(appState.game.packet.name);
            appState.game.loadPacket(combined);
            if (onTiebreakerUsed) {
                onTiebreakerUsed({ ...item, teams: appState.game.teamNames });
            }
        },
        [appState, tiebreakers, onTiebreakerUsed]
    );
    // After a tossup is thrown out, the packet can run out of questions before
    // the game does. When that happens, sub in the next unused tiebreaker
    // automatically. Already-added tiebreakers are recognized by their question
    // text (rather than a counter), so this survives page reloads.
    const subInIfNeeded = React.useCallback((): boolean => {
        const game = appState.game;
        if (tiebreakers == undefined || tiebreakers.length === 0 || !game.isLoaded || game.cycles.length === 0) {
            return false;
        }
        if (game.getTossup(game.playableCycles.length - 1) != undefined) {
            // The packet still covers every playable question; nothing to do.
            return false;
        }
        const existing = new Set(game.packet.tossups.map((t) => t.question));
        const index = tiebreakers.findIndex((tb) => !existing.has(he.decode(tb.question)));
        if (index < 0) {
            return false;
        }
        addTiebreaker(index);
        return true;
    }, [appState, tiebreakers, addTiebreaker]);

    const tiebreakerValue: ITiebreakerContextValue | undefined = React.useMemo(
        () => (tiebreakers && tiebreakers.length > 0 ? { tiebreakers, addTiebreaker, subInIfNeeded } : undefined),
        [tiebreakers, addTiebreaker, subInIfNeeded]
    );

    // We only want to run this effect once, which requires passing in an empty array of dependencies
    // eslint-disable-next-line react-hooks/exhaustive-deps
    // Shared state: hand every persisted snapshot to the host, except the one that merely echoes a snapshot the
    // host just asked us to apply (otherwise two synced moderators would bounce the same game back and forth).
    const persistedStateRef = React.useRef(props.onPersistedState);
    persistedStateRef.current = props.onPersistedState;
    const lastAppliedRef = React.useRef<string | undefined>(undefined);
    // Ready once any saved game has been restored. Host-driven changes to the game wait for this, so a restore
    // finishing late can't overwrite them (or be mistaken for them).
    const [ready, setReady] = React.useState(false);
    React.useEffect(
        () =>
            initializeControl(
                appState,
                {
                    ...props,
                    persistState: props.persistState ?? true,
                    onPersistedState: (json: string) => {
                        if (json === lastAppliedRef.current) {
                            return;
                        }
                        persistedStateRef.current?.(json);
                    },
                },
                () => setReady(true)
            ),
        []
    );

    // Tell the host whether there's a game, so it can offer its own way of starting one when there isn't.
    const onGameLoadedChange = props.onGameLoadedChange;
    React.useEffect(() => {
        if (!ready || onGameLoadedChange == undefined) {
            return;
        }
        return reaction(
            () => appState.game.isLoaded,
            (loaded) => onGameLoadedChange(loaded),
            { fireImmediately: true }
        );
    }, [appState, ready, onGameLoadedChange]);

    // A game the host started: each new object is a new game.
    const hostNewGame = props.hostNewGame;
    const hostGameFormat = props.gameFormat;
    React.useEffect(() => {
        if (!ready || hostNewGame == undefined) {
            return;
        }
        if (hostNewGame.confirm) {
            openHostNewGameDialog(appState, hostNewGame, hostNewGame.gameFormat ?? hostGameFormat);
        } else {
            startHostNewGame(appState, hostNewGame);
        }
        // Only a new game object starts a game; the format changing on its own doesn't.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [appState, ready, hostNewGame]);

    // Competitors who come and go: bring the game's teams and who is active in line with the host's list whenever
    // either changes, or the reader moves on. Watching the game's teams means a game restored or replaced from
    // elsewhere (another moderator's screen) is caught up too.
    const liveTeams = props.liveTeams;
    // The furthest question reached in this game, so a reader stepping back to fix an earlier score doesn't make
    // anyone's arrival or departure look like it happened back there. Kept across changes to the list.
    const furthestRef = React.useRef<{ packet: PacketState | undefined; furthest: number }>({
        packet: undefined,
        furthest: 0,
    });
    React.useEffect(() => {
        if (!ready || liveTeams == undefined) {
            return;
        }
        return reaction(
            () => ({
                loaded: appState.game.isLoaded,
                teams: appState.game.teamNames.join("\n"),
                cycle: appState.uiState.cycleIndex,
                packet: appState.game.packet,
            }),
            (current) => {
                const mark = furthestRef.current;
                if (current.packet !== mark.packet) {
                    mark.packet = current.packet;
                    mark.furthest = 0;
                }
                mark.furthest = Math.max(mark.furthest, current.cycle);
                syncLiveTeams(appState, liveTeams, mark.furthest);
            },
            { fireImmediately: true }
        );
    }, [appState, ready, liveTeams]);

    // The host's theme wins over the one MODAQ saved with its state (so it's applied again once that's restored);
    // the moderator flipping MODAQ's own option is handed back to the host.
    const darkMode = props.darkMode;
    React.useEffect(() => {
        if (ready && darkMode != undefined && appState.uiState.useDarkMode !== darkMode) {
            appState.uiState.toggleDarkMode();
        }
    }, [appState, ready, darkMode]);
    const darkModeRef = React.useRef({ darkMode, onChange: props.onDarkModeChange });
    darkModeRef.current = { darkMode, onChange: props.onDarkModeChange };
    React.useEffect(() => {
        if (!ready) {
            return;
        }
        return reaction(
            () => appState.uiState.useDarkMode,
            (dark) => {
                const host = darkModeRef.current;
                if (host.onChange != undefined && dark !== host.darkMode) {
                    host.onChange(dark);
                }
            }
        );
    }, [appState, ready]);

    const hostNewGameValue: IHostNewGameContextValue = React.useMemo(
        () => ({ onNewGameRequested: props.onNewGameRequested }),
        [props.onNewGameRequested]
    );

    const onExported = props.onExported;
    React.useEffect(() => {
        if (onExported == undefined) {
            return;
        }
        return reaction(
            () => ({ isLoaded: appState.game.isLoaded, hasUpdates: appState.game.hasUpdates }),
            (current, previous) => {
                if (previous != undefined && previous.isLoaded && current.isLoaded && previous.hasUpdates && !current.hasUpdates) {
                    onExported();
                }
            }
        );
    }, [appState, onExported]);

    const remoteState = props.remoteState;
    React.useEffect(() => {
        if (remoteState == undefined) {
            return;
        }
        try {
            const snapshot = JSON.parse(remoteState.json);
            // A host that owns the theme keeps this screen's: one moderator's dark mode isn't the other's, and two
            // screens each putting theirs back would bounce the game between them forever.
            if (props.darkMode != undefined && snapshot?.uiState != undefined) {
                snapshot.uiState.useDarkMode = appState.uiState.useDarkMode;
            }
            parseStore(appState, snapshot, false);
            lastAppliedRef.current = JSON.stringify(appState);
        } catch {
            /* a bad snapshot from the host must not take down the reader */
        }
        // Only a new snapshot is applied; the theme changing on its own isn't one.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [appState, remoteState]);

    React.useEffect(() => update(appState, props), [appState, props]);

    // Live stats sync: whenever the game changes, hand the host the current QBJ
    // (debounced so a burst of edits collapses into one push).
    // Held in a ref, so a host passing a new function on each render doesn't re-subscribe the reaction -- which
    // would cancel the pending (debounced) update every time, and in a busy room the update would never land.
    const onGameUpdateRef = React.useRef(props.onGameUpdate);
    onGameUpdateRef.current = props.onGameUpdate;
    const hasGameUpdate: boolean = props.onGameUpdate != undefined;
    React.useEffect(() => {
        if (!hasGameUpdate) {
            return;
        }
        let timer: ReturnType<typeof setTimeout> | undefined;
        const dispose = reaction(
            // Track the last change and whether a game is loaded, so the first
            // sync fires as soon as the game is created (New Game), not only
            // after the first scoring change. Also track the question index:
            // reaching the last playable question flips the game to "final"
            // even when no scoring change accompanies it (e.g. a dead tossup).
            () => ({
                lastUpdate: appState.game.lastUpdate,
                isLoaded: appState.game.isLoaded,
                cycleIndex: appState.uiState.cycleIndex,
                // A new game replacing one that was loaded changes neither of the above when both sit at the first
                // question, so the packet and the players are watched too.
                packet: appState.game.packet,
                players: appState.game.players.length,
            }),
            () => {
                if (timer != undefined) {
                    clearTimeout(timer);
                }
                timer = setTimeout(() => {
                    if (appState.game.isLoaded) {
                        try {
                            // Same condition as the Next button turning into Export.
                            const inProgress: boolean =
                                appState.uiState.cycleIndex + 1 < appState.game.playableCycles.length;
                            const hasBonuses: boolean =
                                appState.game.gameFormat.tossupsOnly !== true &&
                                appState.game.packet.bonuses.length > 0;
                            const protests: IGameUpdateProtest[] = [];
                            appState.game.playableCycles.forEach((cycle, i) => {
                                for (const p of cycle.tossupProtests ?? []) {
                                    protests.push({
                                        cycle: i + 1,
                                        type: "tossup",
                                        team: p.teamName,
                                        question: p.questionIndex + 1,
                                        position: p.position + 1,
                                        givenAnswer: p.givenAnswer ?? "",
                                    });
                                }
                                for (const p of cycle.bonusProtests ?? []) {
                                    protests.push({
                                        cycle: i + 1,
                                        type: "bonus",
                                        team: p.teamName,
                                        question: p.questionIndex + 1,
                                        part: p.partIndex + 1,
                                        givenAnswer: p.givenAnswer ?? "",
                                    });
                                }
                            });
                            // The packet's category line per tossup, in packet
                            // order (QBJ carries a tossup's packet number but
                            // not its metadata).
                            const categories: string[] = appState.game.packet.tossups.map(
                                (t) => t.metadata ?? ""
                            );
                            // ...and the answer lines, for a host running a
                            // playtest, where the room is meant to see what the
                            // answer was once it has finished the cycle.
                            const answers: string[] = appState.game.packet.tossups.map((t) => t.answer ?? "");
                            // ...and the questions themselves, for a host that
                            // shows the room what it has already played.
                            const questions: string[] = appState.game.packet.tossups.map((t) => t.question ?? "");
                            onGameUpdateRef.current?.(
                                QBJ.toQBJ(appState.game, appState.uiState.packetFilename),
                                inProgress,
                                appState.uiState.cycleIndex + 1,
                                hasBonuses,
                                protests,
                                categories,
                                answers,
                                questions
                            );
                        } catch {
                            /* a transient inconsistent state shouldn't crash the reader */
                        }
                    }
                    // Short enough that the room sees a ruling land as it is made (Klaxon pops it over each
                    // player's buzzer), long enough that a run of bonus-part clicks goes out as one update
                }, 400);
            }
        );
        return () => {
            if (timer != undefined) {
                clearTimeout(timer);
            }
            dispose();
        };
    }, [appState, hasGameUpdate]);

    // Buzz judgments: fire when the reader marks a buzz correct or wrong on the
    // question being read (not when revisiting an already-judged question), so a
    // host with its own buzzer can clear the buzz queue.
    const onBuzzJudged = props.onBuzzJudged;
    React.useEffect(() => {
        if (onBuzzJudged == undefined) {
            return;
        }
        return reaction(
            () => {
                // Track lastUpdate: it's bumped by every cycle event, and reading cycles[i] before the game
                // loads is an out-of-bounds array read that MobX doesn't track, which would leave this
                // reaction dormant for the rest of the game.
                const cycleIndex: number = appState.uiState.cycleIndex;
                const cycle: Cycle | undefined =
                    cycleIndex < appState.game.cycles.length ? appState.game.cycles[cycleIndex] : undefined;
                const correctCount: number = cycle?.correctBuzz ? 1 : 0;
                const judgedCount: number = cycle == undefined ? 0 : correctCount + (cycle.wrongBuzzes?.length ?? 0);
                return {
                    isLoaded: appState.game.isLoaded,
                    lastUpdate: appState.game.lastUpdate,
                    cycleIndex,
                    judgedCount,
                    correctCount,
                };
            },
            (current, previous) => {
                // previous.isLoaded filters out persisted-state restoration on page load, which can bump the
                // judged count without the reader judging anything.
                if (
                    previous != undefined &&
                    previous.isLoaded &&
                    current.cycleIndex === previous.cycleIndex &&
                    current.judgedCount > previous.judgedCount
                ) {
                    onBuzzJudged(current.correctCount > previous.correctCount);
                }
            }
        );
    }, [appState, onBuzzJudged]);
    React.useEffect(() => {
        if (props.gameFormat != undefined) {
            appState.game.setGameFormat(props.gameFormat);
        }
    }, [appState, props.gameFormat]);

    // Keep the question being read inside the game being read. Loading another
    // packet, restoring an archived one, or a throw-out can all leave the index
    // past the end of the cycles that now exist, and every screen that draws
    // "the current cycle" then draws undefined.
    const cycleCount: number = appState.game.cycles.length;
    React.useEffect(() => {
        if (cycleCount > 0 && appState.uiState.cycleIndex > cycleCount - 1) {
            appState.uiState.setCycleIndex(cycleCount - 1);
        }
    }, [appState, cycleCount, appState.uiState.cycleIndex]);
    React.useEffect(() => {
        if (props.packet != undefined) {
            const packet: PacketState | undefined = PacketLoaderController.loadPacket(
                appState,
                props.packet,
                props.packet.name
            );
            if (packet) {
                appState.game.loadPacket(packet);
            }

            // The "Packet loaded" message from this initial load has no UI surface of its own; clear it so it
            // doesn't leak into other UI (e.g. the Add Questions dialog) that reads packetParseStatus.
            appState.uiState.clearPacketStatus();
        }
    }, [appState, props.packet]);
    React.useEffect(() => {
        if (props.players != undefined) {
            appState.game.setPlayers(
                props.players
                    .filter((player) => player != undefined)
                    .map((player) => new Player(player.name, player.teamName, player.isStarter))
            );
        }
    }, [appState, props.players]);

    const theme: Theme = React.useMemo(
        () =>
            createTheme({
                // isInverted doesn't seem to work for creating a dark mode, so use a specific theme that is close enough
                palette: appState.uiState.useDarkMode ? darkModePalette : lightModePalette,
            }),
        [appState.uiState.useDarkMode]
    );

    const newGameNoticeValue: INewGameNoticeContextValue = React.useMemo(
        () => ({ notice: props.newGameNotice }),
        [props.newGameNotice]
    );

    const applyTo = props.applyStylingToRoot ? "body" : "element";

    return (
        <ErrorBoundary appState={appState}>
            <StateProvider appState={appState}>
                <NewGameNoticeContext.Provider value={newGameNoticeValue}>
                <HostNewGameContext.Provider value={hostNewGameValue}>
                <TiebreakerContext.Provider value={tiebreakerValue}>
                <BelowTossupContext.Provider value={props.belowTossup}>
                    <ThemeProvider theme={theme} applyTo={applyTo}>
                        <div className="modaq-control">
                            <GameViewer />
                            <ModalDialogContainer />
                        </div>
                    </ThemeProvider>
                </BelowTossupContext.Provider>
                </TiebreakerContext.Provider>
                </HostNewGameContext.Provider>
                </NewGameNoticeContext.Provider>
            </StateProvider>
        </ErrorBoundary>
    );
});

// We can't use observables here since the user could pass in different instances of IModaqControlProps
// TODO: Should take a callback and settings for export (which ones are enabled, any new export options with a callback
// of game state/QBJ file?)
// A pending protest, as passed to onGameUpdate: everything the room already
// heard out loud (who protested what, and the answer they gave) — never the
// moderator's private notes.
export interface IGameUpdateProtest {
    cycle: number; // 1-based cycle the protest belongs to
    type: "tossup" | "bonus";
    team: string;
    question: number; // 1-based question number as MODAQ shows it
    part?: number; // 1-based bonus part
    position?: number; // 1-based word index of the buzz (tossup protests)
    givenAnswer: string;
}

export interface IModaqControlProps {
    /**
     * If `true`, applies theming to the body, so the background in dark mode will be black evne outside of MODAQ
     */
    applyStylingToRoot?: boolean;

    /**
     * The version that appears when clicking on Help.
     */
    buildVersion?: string;

    /**
     * If defined, this adds another way for game results to get exported. The provided callback will be given the game
     * at the time of export.
     */
    customExport?: ICustomExport;

    /**
     * Initial errata for the current packet, e.g. loaded from a server. Adopted whenever this reference changes.
     */
    errata?: IErratum[];

    /**
     * Called whenever the moderator adds, edits, or removes an erratum, with the full new errata list. The errata UI
     * is always available; this is for hosts that want to save errata themselves instead of (or in addition to)
     * having the moderator export them to a file.
     */
    onErrataChange?: (errata: IErratum[]) => void;

    /**
     * Called (debounced) with the game's QBJ whenever the game changes — buzzes, bonus answers, subs, etc. Lets the
     * host keep a live copy of the match stats in sync without the moderator clicking export. inProgress is true
     * until the reader reaches the last playable question (the same point where Next becomes Export), so hosts can
     * avoid counting a half-played game as final. currentQuestion is the 1-based question the reader is on, so a
     * host can show live scoreboards with game progress. categories carries the loaded packet's per-tossup metadata
     * line, indexed by packet tossup number - 1 (empty string where a tossup has none), so a host can label questions
     * by category. answers carries the packet's answer LINES the same way, for a host running a playtest that
     * shows the room what the answer was once a cycle is over.
     *
     * questions carries the tossup text itself, for a host that shows the room the questions it has already
     * played.
     *
     * All three cover the WHOLE packet, including tossups nobody has heard yet, so a host that shows any of them
     * to players must gate them itself. (The answer line and the question text especially: between them they are
     * the entire packet, some of which is still to be read in that very room.)
     */
    onGameUpdate?: (
        qbj: IMatch,
        inProgress?: boolean,
        currentQuestion?: number,
        hasBonuses?: boolean,
        protests?: IGameUpdateProtest[],
        categories?: string[],
        answers?: string[],
        questions?: string[]
    ) => void;

    /**
     * Called when the reader marks a buzz correct or wrong on the question being read. `correct` says which, so a host
     * with its own buzzer can clear it on a correct answer and move to the next buzz on a wrong one.
     */
    onBuzzJudged?: (correct: boolean) => void;

    /**
     * The player the host's buzzer says is answering (name + team as they appear in the game). The buzz menu lists
     * them first, above the usual per-team listing, so the reader doesn't have to hunt for the name.
     */
    buzzedInPlayer?: { name: string; teamName: string };
    /** How many buzzes the host's buzzer has waiting, the one being judged included. */
    buzzQueueCount?: number;
    /**
     * Take the buzzed-in player's buzz back without scoring it and hand the buzzer to whoever is next. Given, the
     * buzz menu offers it beside Correct/Wrong; a withdrawn buzz is not a wrong answer and leaves no mark on the game.
     */
    onWithdrawBuzz?: () => void;

    /**
     * Called when the game is exported (MODAQ's own JSON/Sheets export or a custom export succeeding) — i.e. whenever
     * the game's pending updates are marked complete while a game is loaded.
     */
    onExported?: () => void;

    /**
     * Called with MODAQ's serialized state (the same JSON it persists to localStorage) each time it is persisted,
     * so a host can keep a shared copy that another device — or a second moderator — can pick up. Requires
     * persistState. Not called for the persist that immediately follows applying `remoteState`.
     */
    onPersistedState?: (json: string) => void;

    /**
     * A serialized state from the host to apply in place (a change made on another moderator's screen). Applied
     * whenever a new object is passed.
     */
    remoteState?: { json: string; seq: number };

    /**
     * Tiebreaker questions the moderator can sub in from the Add Questions dialog.
     */
    tiebreakers?: ITiebreakerItem[];

    /**
     * Called when the moderator subs in a tiebreaker, with the question and the teams that just heard it.
     */
    onTiebreakerUsed?: (info: ITiebreakerItem & { teams: string[] }) => void;

    /**
     * The format of the current game, such as if powers are supported, if tossups are paired with bonuses, etc.
     */
    gameFormat?: IGameFormat;

    /**
     * Needed if you want to support exporting to Google Sheets. This is the client ID of your Google application that
     * connects to the spreadsheet.
     */
    googleClientId?: string;

    /**
     * When `true`, the New Game button in the menu is hidden.
     */
    hideNewGame?: boolean;

    /**
     * If provided and there's no game already loaded (e.g. a fresh start, not a restored one), MODAQ's own New Game
     * dialog is opened prefilled with this packet and — when `rosters` is given — its player pool, so the host can use
     * MODAQ's native team/player entry (with reordering) instead of a custom form.
     */
    newGameOnLoad?: {
        packet: IPacket;
        packetName?: string;
        rosters?: IPlayer[];
        /**
         * Teams to prefill the dialog's manual entry with, so a host that already knows who is playing (e.g. it
         * asked earlier in its own flow) doesn't make the moderator type them again. Takes precedence over
         * `rosters`.
         */
        teams?: { name: string; players: string[] }[];
    };

    /**
     * Content rendered at the top of the New Game dialog, for a host that wants the moderator to review (or go back
     * and change) something it decided before the game starts.
     */
    newGameNotice?: React.ReactNode;

    /**
     * Start a game from the host. Each new object starts a new game (compared by identity), replacing any game that
     * is loaded. With `confirm`, MODAQ's New Game dialog opens prefilled with the packet and teams, for the moderator
     * to check and Start; without it, the game starts at once. Applied after any saved game has been restored.
     *
     * A host should stop passing the object once the game has started: a control mounted later with the same object
     * would start it again.
     */
    hostNewGame?: IHostNewGame;

    /**
     * Called instead of opening the New Game dialog when the moderator chooses New game from the menu, for a host
     * that starts games its own way (with `hostNewGame`). The import commands under New game are unaffected.
     */
    onNewGameRequested?: () => void;

    /**
     * For a game whose competitors come and go — a shootout, where whoever is in the room is playing, including
     * someone who arrives at question 9 and leaves at 15. A present team missing from the loaded game (matched by
     * name) is added, active from the question the reader has reached; a team marked absent stops being active from
     * the next question until it's present again. So each player is credited with the tossups they actually heard.
     * The list is everyone: a team in the game that isn't on it counts as absent. Nobody is ever removed from the
     * game.
     */
    liveTeams?: ILiveTeam[];

    /**
     * Shown under the current tossup's words, above its answer line. Klaxon puts each typed answer there as it is
     * submitted, where the reader is already looking.
     */
    belowTossup?: React.ReactNode;

    /**
     * Called with whether a game is loaded: once when the control is ready (after any saved game is restored), and
     * again whenever that changes.
     */
    onGameLoadedChange?: (loaded: boolean) => void;

    /**
     * Dark mode, for a host with a theme of its own to keep MODAQ in step with. Applied whenever it changes; MODAQ's
     * own Dark mode option still works, and reports through `onDarkModeChange` so the host can follow it.
     */
    darkMode?: boolean;

    /**
     * Called when the moderator turns MODAQ's Dark mode option on or off.
     */
    onDarkModeChange?: (dark: boolean) => void;

    /**
     * If provided, the Add Questions dialog switches to a secret-code lookup mode: instead of uploading a packet
     * file, the user enters an ID, and this callback is given that ID and should resolve to the replacement
     * question packet (an `IPacket`), or an `IStatus` describing why the lookup failed. MODAQ has no knowledge of
     * how or where the question is stored; the host application owns that lookup.
     */
    onFetchQuestionById?: (id: string) => Promise<IPacket | IStatus>;

    /**
     * The packet for the current game. This should only be set once.
     */
    packet?: IPacket;

    /**
     * The name of the packet.
     */
    packetName?: string;

    /**
     * The players in the current game. This should only be set once.
     */
    players?: IPlayer[];

    /**
     * Determines if this control should save state locally so that the same packet, players, and cycle appear when the
     * page is refreshed. This can only be set on the first render.
     */
    persistState?: boolean;

    /**
     * Whether a restored game more than five days old asks to start a new one instead (default true). A host that
     * only ever loads games on purpose — reopening an old one to fix a score — turns it off.
     */
    promptIfOld?: boolean;

    /**
     * If `persistState` is true, then this is the name of the store in localStorge. This can only be set on the first
     * render.
     */
    storeName?: string | undefined;

    /**
     * Settings supplied by the host application to gate host-managed UI behavior: backup-only export,
     * QBJ-only export dialog, substitutions-only roster, and host-managed game format. See
     * {@link IHostSettings} for the individual flags.
     */
    hostSettings?: IHostSettings;

    /**
     * The URL to a Yet Another Packet Parser (YAPP) compatible service, which parses docx files. If this value isn't
     * defined, then packets must be in a JSON format.
     */
    yappServiceUrl?: string;

    /**
     * An optional link shown under the packet picker, for hosts that run their own place to turn a .docx into the
     * JSON MODAQ loads. The host owns both the wording and the address.
     */
    packetParserLink?: IPacketParserLink;
}

// Open MODAQ's own New Game dialog, prefilled by the host with a packet and
// (optionally) a roster player pool, so the moderator sets up teams/players with
// MODAQ's native UI (including reordering). No-op if a game is already loaded.
function maybeOpenHostNewGame(appState: AppState, props: IModaqControlProps): void {
    const spec = props.newGameOnLoad;
    if (spec == undefined || appState.game.isLoaded) {
        return;
    }
    openHostNewGameDialog(appState, spec, props.gameFormat);
}

function openHostNewGameDialog(
    appState: AppState,
    spec: { packet: IPacket; packetName?: string; rosters?: IPlayer[]; teams?: IHostTeam[] },
    gameFormat: IGameFormat | undefined
): void {
    const packetState = PacketLoaderController.loadPacket(appState, spec.packet, spec.packetName);
    appState.uiState.createPendingNewGame();
    if (packetState != undefined) {
        appState.uiState.setPendingNewGamePacket(packetState);
    }
    if (gameFormat != undefined) {
        appState.uiState.setPendingNewGameFormat(gameFormat);
    }
    if (spec.packetName != undefined) {
        appState.uiState.setPacketFilename(spec.packetName);
    }

    // Teams the host already knows: fill in MODAQ's manual entry so the moderator only has to confirm them.
    const teams = (spec.teams ?? []).filter((team) => team != undefined && team.name !== "");
    if (teams.length >= 2) {
        appState.uiState.setPendingNewGameType(PendingGameType.Manual);
        // The team name lives on its players, so a team with nobody in it still
        // needs one (blank) row — which is also where the host expects the
        // moderator to fill the players in.
        const rows = (team: { name: string; players: string[] }): Player[] =>
            team.players.length > 0
                ? team.players.map((name) => new Player(name, team.name, /* isStarter */ true))
                : [new Player("", team.name, /* isStarter */ true)];
        // Every team the host knows about, not just the first two: a shootout
        // hands over one per competitor.
        appState.uiState.setPendingNewGameManualTeams(...teams.map(rows));
        appState.uiState.dialogState.showNewGameDialog();
        return;
    }

    const rosters = (spec.rosters ?? []).filter((player) => player != undefined);
    if (rosters.length > 0) {
        appState.uiState.setPendingNewGameType(PendingGameType.QBJRegistration);
        appState.uiState.setPendingNewGameRosters(
            rosters.map((player) => new Player(player.name, player.teamName, player.isStarter))
        );
    }

    appState.uiState.dialogState.showNewGameDialog();
}

function initializeControl(appState: AppState, props: IModaqControlProps, onReady: () => void): () => void {
    if (props.persistState) {
        configure({ enforceActions: "observed", computedRequiresReaction: true });
        // When the host wants the snapshots, wrap localStorage so it sees every write.
        const onPersistedState = props.onPersistedState;
        const storage =
            onPersistedState == undefined
                ? localStorage
                : {
                      getItem: (key: string): string | null => localStorage.getItem(key),
                      removeItem: (key: string): void => localStorage.removeItem(key),
                      setItem: (key: string, value: string): void => {
                          localStorage.setItem(key, value);
                          onPersistedState(value);
                      },
                  };
        const trunk = new AsyncTrunk(appState, { storage, storageKey: props.storeName, delay: 200 });
        trunk.init(appState).then(() => {
            // Need to check if game is old and prompt the user if they want to restart the game.
            // Date subtraction gives you the number of milliseconds
            const lastUpdate: number | undefined = appState.game.lastUpdate?.getTime();
            if (props.promptIfOld !== false && lastUpdate && Date.now() - lastUpdate > minAgeToPromptForReset) {
                appState.uiState.dialogState.showOKCancelMessageDialog({
                    title: "Start new game?",
                    message: "The loaded game is over 5 days old. Do you want to start a new game instead?",
                    onOK: () => {
                        appState.uiState.createPendingNewGame();
                        appState.uiState.dialogState.showNewGameDialog();
                    },
                });
            }
            // Only open the host-driven New Game once persistence has restored any in-progress game (so a mid-round
            // refresh doesn't clobber it).
            maybeOpenHostNewGame(appState, props);
            onReady();
        });
    } else {
        maybeOpenHostNewGame(appState, props);
        onReady();
    }

    // We have to add the listener at the document layer, otherwise the event isn't picked up if the user clicks on
    // the empty space
    const keydownListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) => shortcutHandler(event, appState);
    document.addEventListener("keyup", keydownListener);

    // The buzz menu keys get a capture-phase keydown listener so they're seen before the menu's own keyboard
    // handling (which has focus while the menu is open) can react to or swallow them
    const buzzMenuKeyListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) =>
        buzzMenuShortcutHandler(event, appState);
    document.addEventListener("keydown", buzzMenuKeyListener, /* useCapture */ true);

    // While the buzz point is being placed (after the first Space), arrow keys move it. They're handled on keydown
    // so holding one repeats, and in the capture phase so focused controls don't scroll or move focus instead.
    const buzzPointPlacementKeyListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) =>
        buzzPointPlacementShortcutHandler(event, appState);
    document.addEventListener("keydown", buzzPointPlacementKeyListener, /* useCapture */ true);

    // While a tossup is live, 1-8 mark that player's buzz correct and Shift+1-8 wrong. These act on keydown; the
    // same key's keyup must then not also reach shortcutHandler, where numbers toggle bonus parts once a tossup
    // is answered correctly.
    const playerShortcutKeyListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) =>
        playerShortcutHandler(event, appState);
    document.addEventListener("keydown", playerShortcutKeyListener, /* useCapture */ true);

    // Space is the buzz shortcut, but it acts on keyup (above). Stop its keydown from scrolling the page (or
    // clicking a focused button) when it's serving as the shortcut -- i.e. not while typing or in a dialog.
    const preventSpaceScrollListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) => {
        if (
            event.key === " " &&
            !isTextEntryElement(event.target) &&
            appState.uiState.dialogState.visibleDialog === ModalVisibilityStatus.None &&
            !appState.uiState.buzzMenuState.visible
        ) {
            event.preventDefault();
        }
    };
    document.addEventListener("keydown", preventSpaceScrollListener);

    // Clicking a text box while the buzz menu is open — the host's chat, say, which is exactly where someone
    // goes mid-buzz. The menu dismisses itself on an outside click, but it puts focus back where it was (the
    // question word), so the typing that followed drove the shortcuts instead of landing in the box: "can we
    // check" moved the reader two questions on and marked the buzz wrong. Close the menu and hand focus to the
    // box, once Fluent has finished restoring it.
    const textFocusListener: (event: Event) => void = (event: Event) => {
        if (!appState.uiState.buzzMenuState.visible || !isTextEntryElement(event.target)) {
            return;
        }
        appState.uiState.hideBuzzMenu();
        const element: HTMLElement = event.target as HTMLElement;
        setTimeout(() => {
            if (element.isConnected) {
                element.focus();
            }
        }, 0);
    };
    document.addEventListener("pointerdown", textFocusListener, /* useCapture */ true);

    return () => {
        document.removeEventListener("keyup", keydownListener);
        document.removeEventListener("keydown", buzzMenuKeyListener, /* useCapture */ true);
        document.removeEventListener("keydown", buzzPointPlacementKeyListener, /* useCapture */ true);
        document.removeEventListener("keydown", playerShortcutKeyListener, /* useCapture */ true);
        document.removeEventListener("keydown", preventSpaceScrollListener);
        document.removeEventListener("pointerdown", textFocusListener, /* useCapture */ true);
    };
}

// Whether the event targets a text-entry control, where keys (notably Space) should be typed rather than treated
// as moderator shortcuts.
function isTextEntryElement(target: EventTarget | null): boolean {
    const element: HTMLElement | null = target as HTMLElement | null;
    if (element == null || element.tagName == undefined) {
        return false;
    }

    const tagName: string = element.tagName;
    return tagName === "INPUT" || tagName === "TEXTAREA" || element.isContentEditable === true;
}

// While the buzz menu is open, number keys pick a player and C/W mark their buzz as correct/wrong, and
// Shift+Left/Shift+Right nudge the buzz point to the exact word. These keys only act this way while the menu is
// open, so the bonus shortcuts in shortcutHandler still work normally.
function buzzMenuShortcutHandler(event: KeyboardEvent, appState: AppState): void {
    if (
        appState.uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None ||
        !appState.uiState.buzzMenuState.visible
    ) {
        return;
    }

    // Not while someone is typing. This listener is on the capture phase, so it sees the key before the field
    // does and would otherwise take it: with the buzz menu open -- which is exactly when there is something to
    // talk about -- "c" in the host's chat box marked the buzz correct instead of typing a letter.
    if (isTextEntryElement(event.target)) {
        return;
    }

    // Shift+Left/Shift+Right move the buzz point one word earlier/later, following the reading order. (Plain
    // arrows are left to the menu's own navigation.) Moving the selected word re-anchors the open menu to it.
    if (event.shiftKey && event.key === "ArrowLeft") {
        TossupQuestionController.moveBuzzPoint(appState, -1);
    } else if (event.shiftKey && event.key === "ArrowRight") {
        TossupQuestionController.moveBuzzPoint(appState, 1);
    } else {
        const key: string = event.key.toUpperCase();
        if (key.length === 1 && key >= "1" && key <= "9") {
            TossupQuestionController.selectBuzzMenuPlayerByNumber(appState, Number(key));
        } else if (key === "C" || key === "W") {
            TossupQuestionController.markKeyboardSelectedPlayerBuzz(appState, /* isCorrect */ key === "C");
        } else {
            return;
        }
    }

    event.preventDefault();
    event.stopPropagation();
}

// The keyup of a key whose keydown was already handled as a player shortcut, so it isn't handled twice
let handledPlayerShortcutCode: string | undefined;

// 1-8 mark the player at that position (the player pad's order) correct; Shift+1-8 mark them wrong. They act while
// the tossup is live or the player pad is open; once a tossup is answered, the numbers toggle bonus parts instead.
function playerShortcutHandler(event: KeyboardEvent, appState: AppState): void {
    const uiState: UIState = appState.uiState;
    if (
        uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None ||
        uiState.buzzMenuState.visible ||
        isTextEntryElement(event.target) ||
        event.ctrlKey ||
        event.altKey ||
        event.metaKey
    ) {
        return;
    }

    // Use the physical key, since Shift changes event.key ("1" becomes "!"). C and W mark whoever has the host's
    // buzzer (Klaxon's queue), for a room with more players than number keys.
    const match: RegExpExecArray | null = /^(?:Digit|Numpad)([1-8])$/.exec(event.code);
    const buzzedInKey: boolean =
        (event.code === "KeyC" || event.code === "KeyW") &&
        !event.shiftKey &&
        TossupQuestionController.getBuzzedInPlayerIndex(appState) >= 0;
    const cycle: Cycle | undefined = appState.activeGame.cycles[uiState.cycleIndex];
    if (
        (match == null && !buzzedInKey) ||
        cycle == undefined ||
        (cycle.correctBuzz != undefined && uiState.buzzPointPlacement == undefined)
    ) {
        return;
    }

    event.preventDefault();
    event.stopPropagation();
    if (event.repeat) {
        return;
    }

    handledPlayerShortcutCode = event.code;
    if (match == null) {
        TossupQuestionController.recordBuzzedInPlayerBuzz(appState, /* isCorrect */ event.code === "KeyC");
        return;
    }

    TossupQuestionController.recordPlayerPadBuzz(appState, Number(match[1]) - 1, /* isCorrect */ !event.shiftKey);
}

// While the player pad is open, the arrow keys move the buzz point: Left/Right by a word, Up/Down to the word above
// or below it on the page. Escape closes the pad.
function buzzPointPlacementShortcutHandler(event: KeyboardEvent, appState: AppState): void {
    if (
        appState.uiState.buzzPointPlacement == undefined ||
        appState.uiState.buzzMenuState.visible ||
        appState.uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None ||
        isTextEntryElement(event.target)
    ) {
        return;
    }

    switch (event.key) {
        case "ArrowLeft":
            TossupQuestionController.moveBuzzPoint(appState, -1);
            break;
        case "ArrowRight":
            TossupQuestionController.moveBuzzPoint(appState, 1);
            break;
        case "ArrowUp":
            TossupQuestionController.moveBuzzPointVertically(appState, -1);
            break;
        case "ArrowDown":
            TossupQuestionController.moveBuzzPointVertically(appState, 1);
            break;
        case "Escape":
            TossupQuestionController.cancelBuzzPointPlacement(appState);
            break;
        default:
            return;
    }

    event.preventDefault();
    event.stopPropagation();
}

function shortcutHandler(event: KeyboardEvent, appState: AppState): void {
    // This key's keydown was a player shortcut (playerShortcutHandler); don't treat its keyup as another shortcut
    if (handledPlayerShortcutCode != undefined && event.code === handledPlayerShortcutCode) {
        handledPlayerShortcutCode = undefined;
        event.preventDefault();
        event.stopPropagation();
        return;
    }

    // Disable shortcuts if there's a modal dialog open
    if (appState.uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None) {
        return;
    }

    // Don't hijack keys while the user is typing in a text field (notably Space, the buzz shortcut)
    if (isTextEntryElement(event.target)) {
        return;
    }

    // While the buzz menu is open it handles the keyboard
    if (appState.uiState.buzzMenuState.visible) {
        return;
    }

    switch (event.key.toUpperCase()) {
        case "E":
            // Open the player pad at the end of the tossup
            TossupQuestionController.placeBuzzPointAtEnd(appState);
            event.preventDefault();
            event.stopPropagation();
            break;

        case " ":
            // Space is the buzz shortcut: it marks the buzz point (where the reader is, when the microphone is
            // tracking them) and opens the player pad there
            TossupQuestionController.handleBuzzShortcut(appState);

            event.preventDefault();
            event.stopPropagation();
            break;

        case "N":
            // Same step-by-step order the Next button follows, so the shortcut doesn't skip a bonus
            if (!CycleChooserController.isOnLastStep(appState)) {
                CycleChooserController.next(appState);
            }
            event.preventDefault();
            event.stopPropagation();

            break;

        case "P":
            CycleChooserController.previous(appState);
            event.preventDefault();
            event.stopPropagation();
            break;

        case "1":
        case "2":
        case "3":
        case "4":
        case "5":
            // This shortcut is only supported when bouncebacks are disabled. We could add support for it later and just
            // toggle through all the fields, but the logic is slightly more complicated and very few formats use
            // bouncebacks.
            if (appState.activeGame.gameFormat.bonusesBounceBack) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            // If there are bonuses and they are active, toggle the bonus part. We have to do some defensive checks to
            // make sure that we can update the bonus
            const cycleIndex: number = appState.uiState.cycleIndex;
            // A game that has just been swapped underneath us can be shorter
            // than the one before it — a 23-question packet followed by a
            // 20-question one — and the index outlives the game it belonged
            // to. Reading the cycle without asking whether it exists is what
            // put "Cannot read properties of undefined (reading 'correctBuzz')"
            // on the screen instead of a reader's game.
            const cycle: Cycle | undefined = appState.activeGame.cycles[cycleIndex];
            const bonus: Bonus | undefined = appState.activeGame.getBonus(cycleIndex);
            if (cycle?.correctBuzz == undefined || bonus == undefined) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            // We know event.key is a number here, so we don't need to check for NaN
            const partIndex: number = Number(event.key) - 1;
            if (bonus.parts.length <= partIndex) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            const teamName: string = cycle.correctBuzz.marker.player.teamName;
            const currentPoints: number | undefined = cycle.bonusAnswer?.parts[partIndex].points ?? 0;

            cycle.setBonusPartAnswer(partIndex, teamName, currentPoints > 0 ? 0 : bonus.parts[partIndex].value);

            event.preventDefault();
            event.stopPropagation();
            break;
        default:
            break;
    }
}

function update(appState: AppState, props: IModaqControlProps): void {
    if (props.buildVersion !== appState.uiState.buildVersion) {
        appState.uiState.setBuildVersion(props.buildVersion);
    }

    if (props.googleClientId !== appState.uiState.sheetsState.clientId) {
        appState.uiState.sheetsState.setClientId(props.googleClientId);
    }

    if (props.yappServiceUrl !== appState.uiState.yappServiceUrl) {
        appState.uiState.setYappServiceUrl(props.yappServiceUrl);
    }

    if (props.packetParserLink !== appState.uiState.packetParserLink) {
        appState.uiState.setPacketParserLink(props.packetParserLink);
    }

    if (props.gameFormat != undefined && props.gameFormat !== appState.game.gameFormat) {
        appState.game.setGameFormat(props.gameFormat);
    }

    if (props.customExport != appState.uiState.customExportOptions) {
        if (props.customExport == undefined) {
            appState.uiState.resetCustomExport();
            appState.setCustomExportInterval(undefined);
        } else {
            const updateInterval: boolean =
                props.customExport.customExportInterval !== appState.uiState.customExportOptions?.customExportInterval;

            appState.uiState.setCustomExport(props.customExport);
            if (updateInterval) {
                appState.setCustomExportInterval(props.customExport.customExportInterval);
            }
        }
    }

    if (props.hideNewGame !== appState.uiState.hideNewGame) {
        appState.uiState.setHideNewGame(props.hideNewGame == true);
    }

    const buzzedIn = props.buzzedInPlayer;
    const currentBuzzedIn = appState.uiState.buzzedInPlayer;
    if (
        (buzzedIn?.name ?? "") !== (currentBuzzedIn?.name ?? "") ||
        (buzzedIn?.teamName ?? "") !== (currentBuzzedIn?.teamName ?? "")
    ) {
        appState.uiState.setBuzzedInPlayer(buzzedIn);
    }

    const queueCount = props.buzzQueueCount ?? 0;
    const currentHostBuzzer = appState.uiState.hostBuzzer;
    if (queueCount !== (currentHostBuzzer?.queueCount ?? 0) || props.onWithdrawBuzz !== currentHostBuzzer?.onWithdraw) {
        appState.uiState.setHostBuzzer({ queueCount, onWithdraw: props.onWithdrawBuzz });
    }

    const nextHostSettings: IHostSettings | undefined = props.hostSettings;
    const currentHostSettings = appState.uiState.hostSettings;
    if (
        (nextHostSettings?.promptBeforeExport ?? false) !== currentHostSettings.promptBeforeExport ||
        (nextHostSettings?.onlyAllowQbjExport ?? false) !== currentHostSettings.onlyAllowQbjExport ||
        (nextHostSettings?.restrictRosterChanges ?? false) !== currentHostSettings.restrictRosterChanges ||
        (nextHostSettings?.disableChangeFormat ?? false) !== currentHostSettings.disableChangeFormat ||
        nextHostSettings?.productName !== currentHostSettings.productName
    ) {
        appState.uiState.setHostSettings(nextHostSettings);
    }

    if (props.onFetchQuestionById !== appState.uiState.onFetchQuestionById) {
        appState.uiState.setOnFetchQuestionById(props.onFetchQuestionById);
    }

    if (props.packetName !== appState.uiState.packetFilename && props.packetName !== appState.game.packet.name) {
        if (props.packetName != undefined) {
            appState.uiState.setPacketFilename(props.packetName);
            if (appState.game.packet) {
                appState.game.packet.setName(props.packetName);
            }
        } else {
            appState.uiState.resetPacketFilename();
        }
    }
}

interface IErrorBoundaryProps {
    appState: AppState;
}

interface IErrorBoundaryState {
    error: Error | string | undefined;
    showClearPrompt: boolean;
}

class ErrorBoundary extends React.Component<IErrorBoundaryProps, IErrorBoundaryState> {
    private static readonly dialogContent: IDialogContentProps = {
        type: DialogType.normal,
        title: "Reset",
        closeButtonAriaLabel: "Close",
        subText: "Do you wish to reset the reader? You will lose your current game.",
    };

    private static readonly exportButtonStyle: IButtonStyles = {
        root: {
            marginRight: 20,
            marginTop: 20,
        },
    };

    constructor(props: IErrorBoundaryProps) {
        super(props);

        this.state = { error: undefined, showClearPrompt: false };
    }

    static getDerivedStateFromError(error: Error | string): IErrorBoundaryState {
        // Update state so the next render will show the fallback UI.
        return { error, showClearPrompt: false };
    }

    // // componentDidCatch(error, errorInfo) {
    // //     // You can also log the error to an error reporting service. We don't have a logging service for this
    // // }

    public render() {
        if (this.state.error) {
            const text: string = "Error: " + this.state.error;

            // This shouldn't re-render often, and the user should leave the page soon when this appears, so skip
            // memoization
            const onClear = (): void => {
                const trunk = new AsyncTrunk(this.props.appState, { storage: localStorage, delay: 100 });
                trunk.clear();
                location.reload();
            };

            const hideDialog = (): void => {
                this.setState({ showClearPrompt: false });
            };

            const showDialog = (): void => {
                this.setState({ showClearPrompt: true });
            };

            const gameJson: Blob = new Blob([JSON.stringify(this.props.appState.game, null, 2)], {
                type: "application/json",
            });
            const url = URL.createObjectURL(gameJson);

            return (
                <Stack>
                    <StackItem>
                        <h2>Something went wrong</h2>
                    </StackItem>
                    <StackItem>
                        <Label>{text}</Label>
                    </StackItem>
                    <StackItem>
                        <Label>
                            Refreshing the page fixes most errors. If you keep seeing errors, click on the first button
                            to copy the JSON of all the events, then click on the second button to reset the app.
                        </Label>
                    </StackItem>
                    <StackItem>
                        <PrimaryButton
                            aria-label="Export game (JSON)"
                            text="Export game (JSON)"
                            styles={ErrorBoundary.exportButtonStyle}
                            href={url}
                            download="QuizBowlReader_Game_Error.json"
                        />
                        <DefaultButton onClick={showDialog} text="Reset" />
                    </StackItem>
                    <Dialog
                        hidden={!this.state.showClearPrompt}
                        onDismiss={hideDialog}
                        dialogContentProps={ErrorBoundary.dialogContent}
                    >
                        <DialogFooter>
                            <PrimaryButton onClick={onClear} text="OK" />
                            <DefaultButton onClick={hideDialog} text="Cancel" />
                        </DialogFooter>
                    </Dialog>
                </Stack>
            );
        }

        return this.props.children;
    }
}

export default ModaqControl;
