import React from "react";
import {
    IDialogContentProps,
    DialogType,
    IButtonStyles,
    Stack,
    StackItem,
    Label,
    PrimaryButton,
    DefaultButton,
    Dialog,
    DialogFooter,
    initializeIcons,
    ThemeProvider,
    createTheme,
    Theme,
    IPalette,
} from "@fluentui/react";
import { AsyncTrunk } from "mobx-sync";
import { configure, reaction } from "mobx";
import { observer } from "mobx-react-lite";
import he from "he";

import * as PacketLoaderController from "./PacketLoaderController";
import * as TossupQuestionController from "./TossupQuestionController";
import { StateProvider } from "../contexts/StateContext";
import { ErrataContext, IErrataContextValue } from "../contexts/ErrataContext";
import { IErratum } from "../state/IErratum";
import { TiebreakerContext, ITiebreakerContextValue, ITiebreakerItem } from "../contexts/TiebreakerContext";
import * as QBJ from "../qbj/QBJ";
import { IMatch } from "../qbj/QBJ";
import { AppState } from "../state/AppState";
import { GameViewer } from "./GameViewer";
import { ModalDialogContainer } from "./ModalDialogContainer";
import { IGameFormat } from "../state/IGameFormat";
import { IPacket } from "../state/IPacket";
import { IPlayer, Player } from "../state/TeamState";
import { PendingGameType } from "../state/IPendingNewGame";
import { Bonus, ITossupWord, PacketState, Tossup } from "../state/PacketState";
import { ICustomExport } from "../state/CustomExport";
import { Cycle } from "../state/Cycle";
import { ModalVisibilityStatus } from "../state/ModalVisibilityStatus";

// Initialize Fluent UI icons when this is loaded, before the first render
initializeIcons();

// We may want to make this customizable, but for now set it to 5 days
const minAgeToPromptForReset = 5 * 1000 * 60 * 60 * 24; // 5 days in ms

const lightModePalette: Partial<IPalette> = {
    themePrimary: "#0078d4",
    themeLighterAlt: "#eff6fc",
    themeLighter: "#deecf9",
    themeLight: "#c7e0f4",
    themeTertiary: "#71afe5",
    themeSecondary: "#2b88d8",
    themeDarkAlt: "#106ebe",
    themeDark: "#005a9e",
    themeDarker: "#004578",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralSecondaryAlt: "#8a8886",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
};

// Generated by going to https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html
// and using the inverse for each of the three main colors. This looks better than swapping black/white values for
// lightModePalette
const darkModePalette: Partial<IPalette> = {
    themePrimary: "#0078d4",
    themeLighterAlt: "#000508",
    themeLighter: "#001322",
    themeLight: "#00243f",
    themeTertiary: "#00487f",
    themeSecondary: "#006aba",
    themeDarkAlt: "#1684d8",
    themeDark: "#3595de",
    themeDarker: "#66afe7",
    neutralLighterAlt: "#0b0b0b",
    neutralLighter: "#151515",
    neutralLight: "#252525",
    neutralQuaternaryAlt: "#2f2f2f",
    neutralQuaternary: "#373737",
    neutralTertiaryAlt: "#595959",
    neutralTertiary: "#f3f3f3",
    neutralSecondary: "#f5f5f5",
    neutralSecondaryAlt: "#757779", // This is going to be the inverse of light's neutralSecondaryAlt, so there's some distinguishment between neutral secondary
    neutralPrimaryAlt: "#f7f7f7",
    neutralPrimary: "#eeeeee",
    neutralDark: "#fbfbfb",
    black: "#fdfdfd",
    white: "#000000",
};

export const ModaqControl = observer(function ModaqControl(props: IModaqControlProps): JSX.Element {
    const [appState]: [AppState, React.Dispatch<React.SetStateAction<AppState>>] = React.useState(() => new AppState());

    // Errata are host-owned (persisted to the tournament by the embedder), kept
    // in plain React state so they're independent of the game/persistence.
    const [errata, setErrata] = React.useState<IErratum[]>(props.errata ?? []);
    const onErrataChange = props.onErrataChange;

    // Adopt errata the host passes in (e.g. loaded from the server) when that
    // reference changes.
    React.useEffect(() => {
        if (props.errata != undefined) {
            setErrata(props.errata);
        }
    }, [props.errata]);

    const setErratum = React.useCallback(
        (erratum: IErratum): void => {
            setErrata((previous) => {
                const next: IErratum[] = [
                    ...previous.filter(
                        (existing) =>
                            !(
                                existing.questionNumber === erratum.questionNumber &&
                                existing.questionType === erratum.questionType
                            )
                    ),
                    { ...erratum, at: erratum.at ?? Date.now() },
                ];
                if (onErrataChange) {
                    onErrataChange(next);
                }
                return next;
            });
        },
        [onErrataChange]
    );

    const removeErratum = React.useCallback(
        (questionNumber: number, questionType: "tossup" | "bonus"): void => {
            setErrata((previous) => {
                const next: IErratum[] = previous.filter(
                    (existing) =>
                        !(existing.questionNumber === questionNumber && existing.questionType === questionType)
                );
                if (onErrataChange) {
                    onErrataChange(next);
                }
                return next;
            });
        },
        [onErrataChange]
    );

    // Only expose the errata context (and thus the errata UI) when the host opts
    // in by providing an onErrataChange handler.
    const errataValue: IErrataContextValue | undefined = React.useMemo(
        () => (onErrataChange ? { errata, setErratum, removeErratum } : undefined),
        [onErrataChange, errata, setErratum, removeErratum]
    );

    // Tiebreakers: append the chosen question to the packet (so the next/thrown-
    // out tossup reads it) and report which teams heard it.
    const tiebreakers = props.tiebreakers;
    const onTiebreakerUsed = props.onTiebreakerUsed;
    const addTiebreaker = React.useCallback(
        (index: number): void => {
            const item = tiebreakers?.[index];
            if (item == undefined) {
                return;
            }
            const combined: PacketState = new PacketState();
            combined.setTossups(
                appState.game.packet.tossups.concat([new Tossup(he.decode(item.question), he.decode(item.answer))])
            );
            combined.setBonuses(appState.game.packet.bonuses);
            combined.setName(appState.game.packet.name);
            appState.game.loadPacket(combined);
            if (onTiebreakerUsed) {
                onTiebreakerUsed({ ...item, teams: appState.game.teamNames });
            }
        },
        [appState, tiebreakers, onTiebreakerUsed]
    );
    // After a tossup is thrown out, the packet can run out of questions before
    // the game does. When that happens, sub in the next unused tiebreaker
    // automatically. Already-added tiebreakers are recognized by their question
    // text (rather than a counter), so this survives page reloads.
    const subInIfNeeded = React.useCallback((): boolean => {
        const game = appState.game;
        if (tiebreakers == undefined || tiebreakers.length === 0 || !game.isLoaded || game.cycles.length === 0) {
            return false;
        }
        if (game.getTossup(game.playableCycles.length - 1) != undefined) {
            // The packet still covers every playable question; nothing to do.
            return false;
        }
        const existing = new Set(game.packet.tossups.map((t) => t.question));
        const index = tiebreakers.findIndex((tb) => !existing.has(he.decode(tb.question)));
        if (index < 0) {
            return false;
        }
        addTiebreaker(index);
        return true;
    }, [appState, tiebreakers, addTiebreaker]);

    const tiebreakerValue: ITiebreakerContextValue | undefined = React.useMemo(
        () => (tiebreakers && tiebreakers.length > 0 ? { tiebreakers, addTiebreaker, subInIfNeeded } : undefined),
        [tiebreakers, addTiebreaker, subInIfNeeded]
    );

    // We only want to run this effect once, which requires passing in an empty array of dependencies
    // eslint-disable-next-line react-hooks/exhaustive-deps
    React.useEffect(() => initializeControl(appState, { ...props, persistState: props.persistState ?? true }), []);

    React.useEffect(() => update(appState, props), [appState, props]);

    // Live stats sync: whenever the game changes, hand the host the current QBJ
    // (debounced so a burst of edits collapses into one push).
    const onGameUpdate = props.onGameUpdate;
    React.useEffect(() => {
        if (onGameUpdate == undefined) {
            return;
        }
        let timer: ReturnType<typeof setTimeout> | undefined;
        const dispose = reaction(
            // Track the last change and whether a game is loaded, so the first
            // sync fires as soon as the game is created (New Game), not only
            // after the first scoring change. Also track the question index:
            // reaching the last playable question flips the game to "final"
            // even when no scoring change accompanies it (e.g. a dead tossup).
            () => ({
                lastUpdate: appState.game.lastUpdate,
                isLoaded: appState.game.isLoaded,
                cycleIndex: appState.uiState.cycleIndex,
            }),
            () => {
                if (timer != undefined) {
                    clearTimeout(timer);
                }
                timer = setTimeout(() => {
                    if (appState.game.isLoaded) {
                        try {
                            // Same condition as the Next button turning into Export.
                            const inProgress: boolean =
                                appState.uiState.cycleIndex + 1 < appState.game.playableCycles.length;
                            onGameUpdate(
                                QBJ.toQBJ(appState.game, appState.uiState.packetFilename),
                                inProgress,
                                appState.uiState.cycleIndex + 1
                            );
                        } catch {
                            /* a transient inconsistent state shouldn't crash the reader */
                        }
                    }
                }, 1200);
            }
        );
        return () => {
            if (timer != undefined) {
                clearTimeout(timer);
            }
            dispose();
        };
    }, [appState, onGameUpdate]);

    // Buzz judgments: fire when the reader marks a buzz correct or wrong on the
    // question being read (not when revisiting an already-judged question), so a
    // host with its own buzzer can clear the buzz queue.
    const onBuzzJudged = props.onBuzzJudged;
    React.useEffect(() => {
        if (onBuzzJudged == undefined) {
            return;
        }
        return reaction(
            () => {
                // Track lastUpdate: it's bumped by every cycle event, and reading cycles[i] before the game
                // loads is an out-of-bounds array read that MobX doesn't track, which would leave this
                // reaction dormant for the rest of the game.
                const cycleIndex: number = appState.uiState.cycleIndex;
                const cycle: Cycle | undefined =
                    cycleIndex < appState.game.cycles.length ? appState.game.cycles[cycleIndex] : undefined;
                const judgedCount: number =
                    cycle == undefined ? 0 : (cycle.correctBuzz ? 1 : 0) + (cycle.wrongBuzzes?.length ?? 0);
                return {
                    isLoaded: appState.game.isLoaded,
                    lastUpdate: appState.game.lastUpdate,
                    cycleIndex,
                    judgedCount,
                };
            },
            (current, previous) => {
                // previous.isLoaded filters out persisted-state restoration on page load, which can bump the
                // judged count without the reader judging anything.
                if (
                    previous != undefined &&
                    previous.isLoaded &&
                    current.cycleIndex === previous.cycleIndex &&
                    current.judgedCount > previous.judgedCount
                ) {
                    onBuzzJudged();
                }
            }
        );
    }, [appState, onBuzzJudged]);
    React.useEffect(() => {
        if (props.gameFormat != undefined) {
            appState.game.setGameFormat(props.gameFormat);
        }
    }, [appState, props.gameFormat]);
    React.useEffect(() => {
        if (props.packet != undefined) {
            const packet: PacketState | undefined = PacketLoaderController.loadPacket(
                appState,
                props.packet,
                props.packet.name
            );
            if (packet) {
                appState.game.loadPacket(packet);
            }
        }
    }, [appState, props.packet]);
    React.useEffect(() => {
        if (props.players != undefined) {
            appState.game.setPlayers(
                props.players
                    .filter((player) => player != undefined)
                    .map((player) => new Player(player.name, player.teamName, player.isStarter))
            );
        }
    }, [appState, props.players]);

    const theme: Theme = React.useMemo(
        () =>
            createTheme({
                // isInverted doesn't seem to work for creating a dark mode, so use a specific theme that is close enough
                palette: appState.uiState.useDarkMode ? darkModePalette : lightModePalette,
            }),
        [appState.uiState.useDarkMode]
    );

    const applyTo = props.applyStylingToRoot ? "body" : "element";

    return (
        <ErrorBoundary appState={appState}>
            <StateProvider appState={appState}>
                <ErrataContext.Provider value={errataValue}>
                    <TiebreakerContext.Provider value={tiebreakerValue}>
                        <ThemeProvider theme={theme} applyTo={applyTo}>
                            <div className="modaq-control">
                                <GameViewer />
                                <ModalDialogContainer />
                            </div>
                        </ThemeProvider>
                    </TiebreakerContext.Provider>
                </ErrataContext.Provider>
            </StateProvider>
        </ErrorBoundary>
    );
});

// We can't use observables here since the user could pass in different instances of IModaqControlProps
// TODO: Should take a callback and settings for export (which ones are enabled, any new export options with a callback
// of game state/QBJ file?)
export interface IModaqControlProps {
    /**
     * If `true`, applies theming to the body, so the background in dark mode will be black evne outside of MODAQ
     */
    applyStylingToRoot?: boolean;

    /**
     * The version that appears when clicking on Help.
     */
    buildVersion?: string;

    /**
     * If defined, this adds another way for game results to get exported. The provided callback will be given the game
     * at the time of export.
     */
    customExport?: ICustomExport;

    /**
     * Initial errata for the current packet, e.g. loaded from a server. Adopted whenever this reference changes.
     */
    errata?: IErratum[];

    /**
     * Called whenever the moderator adds, edits, or removes an erratum, with the full new errata list. Providing this
     * handler is what enables the errata UI.
     */
    onErrataChange?: (errata: IErratum[]) => void;

    /**
     * Called (debounced) with the game's QBJ whenever the game changes — buzzes, bonus answers, subs, etc. Lets the
     * host keep a live copy of the match stats in sync without the moderator clicking export. inProgress is true
     * until the reader reaches the last playable question (the same point where Next becomes Export), so hosts can
     * avoid counting a half-played game as final. currentQuestion is the 1-based question the reader is on, so a
     * host can show live scoreboards with game progress.
     */
    onGameUpdate?: (qbj: IMatch, inProgress?: boolean, currentQuestion?: number) => void;

    /**
     * Called when the reader marks a buzz correct or wrong on the question being read. Hosts with their own buzzer
     * (like Klaxon) can use this to clear the buzz queue once the buzz is resolved.
     */
    onBuzzJudged?: () => void;

    /**
     * Tiebreaker questions the moderator can sub in from the Add Questions dialog.
     */
    tiebreakers?: ITiebreakerItem[];

    /**
     * Called when the moderator subs in a tiebreaker, with the question and the teams that just heard it.
     */
    onTiebreakerUsed?: (info: ITiebreakerItem & { teams: string[] }) => void;

    /**
     * The format of the current game, such as if powers are supported, if tossups are paired with bonuses, etc.
     */
    gameFormat?: IGameFormat;

    /**
     * Needed if you want to support exporting to Google Sheets. This is the client ID of your Google application that
     * connects to the spreadsheet.
     */
    googleClientId?: string;

    /**
     * When `true`, the New Game button in the menu is hidden.
     */
    hideNewGame?: boolean;

    /**
     * If provided and there's no game already loaded (e.g. a fresh start, not a restored one), MODAQ's own New Game
     * dialog is opened prefilled with this packet and — when `rosters` is given — its player pool, so the host can use
     * MODAQ's native team/player entry (with reordering) instead of a custom form.
     */
    newGameOnLoad?: { packet: IPacket; packetName?: string; rosters?: IPlayer[] };

    /**
     * The packet for the current game. This should only be set once.
     */
    packet?: IPacket;

    /**
     * The name of the packet.
     */
    packetName?: string;

    /**
     * The players in the current game. This should only be set once.
     */
    players?: IPlayer[];

    /**
     * Determines if this control should save state locally so that the same packet, players, and cycle appear when the
     * page is refreshed. This can only be set on the first render.
     */
    persistState?: boolean;

    /**
     * If `persistState` is true, then this is the name of the store in localStorge. This can only be set on the first
     * render.
     */
    storeName?: string | undefined;

    /**
     * The URL to a Yet Another Packet Parser (YAPP) compatible service, which parses docx files. If this value isn't
     * defined, then packets must be in a JSON format.
     */
    yappServiceUrl?: string;
}

// Open MODAQ's own New Game dialog, prefilled by the host with a packet and
// (optionally) a roster player pool, so the moderator sets up teams/players with
// MODAQ's native UI (including reordering). No-op if a game is already loaded.
function maybeOpenHostNewGame(appState: AppState, props: IModaqControlProps): void {
    const spec = props.newGameOnLoad;
    if (spec == undefined || appState.game.isLoaded) {
        return;
    }

    const packetState = PacketLoaderController.loadPacket(appState, spec.packet, spec.packetName);
    appState.uiState.createPendingNewGame();
    if (packetState != undefined) {
        appState.uiState.setPendingNewGamePacket(packetState);
    }
    if (props.gameFormat != undefined) {
        appState.uiState.setPendingNewGameFormat(props.gameFormat);
    }
    if (spec.packetName != undefined) {
        appState.uiState.setPacketFilename(spec.packetName);
    }

    const rosters = (spec.rosters ?? []).filter((player) => player != undefined);
    if (rosters.length > 0) {
        appState.uiState.setPendingNewGameType(PendingGameType.QBJRegistration);
        appState.uiState.setPendingNewGameRosters(
            rosters.map((player) => new Player(player.name, player.teamName, player.isStarter))
        );
    }

    appState.uiState.dialogState.showNewGameDialog();
}

function initializeControl(appState: AppState, props: IModaqControlProps): () => void {
    if (props.persistState) {
        configure({ enforceActions: "observed", computedRequiresReaction: true });
        const trunk = new AsyncTrunk(appState, { storage: localStorage, storageKey: props.storeName, delay: 200 });
        trunk.init(appState).then(() => {
            // Need to check if game is old and prompt the user if they want to restart the game.
            // Date subtraction gives you the number of milliseconds
            const lastUpdate: number | undefined = appState.game.lastUpdate?.getTime();
            if (lastUpdate && Date.now() - lastUpdate > minAgeToPromptForReset) {
                appState.uiState.dialogState.showOKCancelMessageDialog({
                    title: "Start new game?",
                    message: "The loaded game is over 5 days old. Do you want to start a new game instead?",
                    onOK: () => {
                        appState.uiState.createPendingNewGame();
                        appState.uiState.dialogState.showNewGameDialog();
                    },
                });
            }
            // Only open the host-driven New Game once persistence has restored any in-progress game (so a mid-round
            // refresh doesn't clobber it).
            maybeOpenHostNewGame(appState, props);
        });
    } else {
        maybeOpenHostNewGame(appState, props);
    }

    // We have to add the listener at the document layer, otherwise the event isn't picked up if the user clicks on
    // the empty space
    const keydownListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) => shortcutHandler(event, appState);
    document.addEventListener("keyup", keydownListener);

    // The buzz menu keys get a capture-phase keydown listener so they're seen before the menu's own keyboard
    // handling (which has focus while the menu is open) can react to or swallow them
    const buzzMenuKeyListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) =>
        buzzMenuShortcutHandler(event, appState);
    document.addEventListener("keydown", buzzMenuKeyListener, /* useCapture */ true);

    // Space is the buzz shortcut, but it acts on keyup (above). Stop its keydown from scrolling the page (or
    // clicking a focused button) when it's serving as the shortcut -- i.e. not while typing or in a dialog.
    const preventSpaceScrollListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) => {
        if (
            event.key === " " &&
            !isTextEntryElement(event.target) &&
            appState.uiState.dialogState.visibleDialog === ModalVisibilityStatus.None &&
            !appState.uiState.buzzMenuState.visible
        ) {
            event.preventDefault();
        }
    };
    document.addEventListener("keydown", preventSpaceScrollListener);

    // Capture phase so it beats the question text's FocusZone to Space/Enter while typing a word number
    const typeBuzzIndexListener: (event: KeyboardEvent) => void = (event: KeyboardEvent) =>
        typeBuzzIndexKeydownHandler(event, appState);
    document.addEventListener("keydown", typeBuzzIndexListener, /* useCapture */ true);

    return () => {
        document.removeEventListener("keyup", keydownListener);
        document.removeEventListener("keydown", buzzMenuKeyListener, /* useCapture */ true);
        document.removeEventListener("keydown", preventSpaceScrollListener);
        document.removeEventListener("keydown", typeBuzzIndexListener, /* useCapture */ true);
    };
}

// Whether the event targets a text-entry control, where keys (notably Space) should be typed rather than treated
// as moderator shortcuts.
function isTextEntryElement(target: EventTarget | null): boolean {
    const element: HTMLElement | null = target as HTMLElement | null;
    if (element == null || element.tagName == undefined) {
        return false;
    }

    const tagName: string = element.tagName;
    return tagName === "INPUT" || tagName === "TEXTAREA" || element.isContentEditable === true;
}

// While the buzz menu is open, number keys pick a player and C/W mark their buzz as correct/wrong, and
// Shift+Left/Shift+Right nudge the buzz point to the exact word. These keys only act this way while the menu is
// open, so the bonus shortcuts in shortcutHandler still work normally.
function buzzMenuShortcutHandler(event: KeyboardEvent, appState: AppState): void {
    if (
        appState.uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None ||
        !appState.uiState.buzzMenuState.visible
    ) {
        return;
    }

    // Shift+Left/Shift+Right move the buzz point one word earlier/later, following the reading order. (Plain
    // arrows are left to the menu's own navigation.) Moving the selected word re-anchors the open menu to it.
    if (event.shiftKey && event.key === "ArrowLeft") {
        TossupQuestionController.moveBuzzPoint(appState, -1);
    } else if (event.shiftKey && event.key === "ArrowRight") {
        TossupQuestionController.moveBuzzPoint(appState, 1);
    } else {
        const key: string = event.key.toUpperCase();
        if (key.length === 1 && key >= "1" && key <= "9") {
            TossupQuestionController.selectBuzzMenuPlayerByNumber(appState, Number(key));
        } else if (key === "C" || key === "W") {
            TossupQuestionController.markKeyboardSelectedPlayerBuzz(appState, /* isCorrect */ key === "C");
        } else {
            return;
        }
    }

    event.preventDefault();
    event.stopPropagation();
}

// Drives "type word number to buzz" mode on a capture-phase keydown, so it runs before the question text's
// FocusZone (which would otherwise turn Space/Enter on a focused word into a click and open the normal buzz
// menu -- the reason this mode didn't work unless the mic happened to hold focus elsewhere). Space starts entry;
// once entering, digits/Enter/Backspace/Escape drive it. Other situations fall through to the normal handlers.
function typeBuzzIndexKeydownHandler(event: KeyboardEvent, appState: AppState): void {
    const uiState = appState.uiState;
    if (
        !uiState.typeBuzzIndexMode ||
        uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None ||
        uiState.buzzMenuState.visible ||
        isTextEntryElement(event.target)
    ) {
        return;
    }

    if (uiState.isEnteringBuzzIndex) {
        buzzIndexEntryHandler(event, appState);
    } else if (event.key === " ") {
        TossupQuestionController.startBuzzIndexEntry(appState);
        event.preventDefault();
        event.stopPropagation();
    }
}

// While typing a word number (Space in "type word number" mode), digits build the number, Enter sets the buzz
// point at that word and opens the buzz menu, Backspace edits the number, and Escape cancels.
function buzzIndexEntryHandler(event: KeyboardEvent, appState: AppState): void {
    if (event.key.length === 1 && event.key >= "0" && event.key <= "9") {
        TossupQuestionController.appendBuzzIndexDigit(appState, event.key);
    } else if (event.key === "Enter") {
        TossupQuestionController.commitBuzzIndexEntry(appState);
    } else if (event.key === "Backspace") {
        TossupQuestionController.backspaceBuzzIndexDigit(appState);
    } else if (event.key === "Escape") {
        TossupQuestionController.cancelBuzzIndexEntry(appState);
    } else {
        return;
    }

    event.preventDefault();
    event.stopPropagation();
}

function shortcutHandler(event: KeyboardEvent, appState: AppState): void {
    // Disable shortcuts if there's a modal dialog open
    if (appState.uiState.dialogState.visibleDialog !== ModalVisibilityStatus.None) {
        return;
    }

    // The buzz menu's keys (numbers, C, W) are handled by buzzMenuShortcutHandler on keydown; while the menu
    // is open, don't let the same keys also trigger the shortcuts below
    if (appState.uiState.buzzMenuState.visible) {
        return;
    }

    // Don't hijack keys while the user is typing in a text field (notably Space, the buzz shortcut)
    if (isTextEntryElement(event.target)) {
        return;
    }

    // While typing a word number, the keys are handled on keydown (typeBuzzIndexKeydownHandler); don't also run
    // the shortcuts below on keyup
    if (appState.uiState.isEnteringBuzzIndex) {
        return;
    }

    switch (event.key.toUpperCase()) {
        case "E":
            // Go to the end of a tossup and open up the buzz menu.
            const tossup: Tossup | undefined = appState.game.getTossup(appState.uiState.cycleIndex);
            if (tossup) {
                // Issue is that this removes parens, so we don't have all the info we need
                const words: ITossupWord[] = tossup.getWords(appState.game.gameFormat);
                const index: number = words.filter((word) => word.canBuzzOn).length - 1;

                appState.uiState.setSelectedWordIndex(index);
                appState.uiState.showBuzzMenu(/* clearSelectedWordOnClose */ false);

                // An alternate approach, if we want to keep keyboard focus there. For now users would probably just
                // keep pressing E, and this way looks uglier (flash of focus, keeps focus after the buzzer is selected)
                // This requires adding the class "word" to the span in QuestionWord.tsx
                // // const index: number = words.length - 1;
                // // const wordElement = document.getElementsByClassName("word").item(index) as HTMLSpanElement;
                // // if (wordElement) {
                // //     wordElement.focus();
                // //     wordElement.click();
                // // }
            }

            event.preventDefault();
            event.stopPropagation();

            break;

        case " ":
            // In "type word number" mode, Space is handled on keydown (typeBuzzIndexKeydownHandler) so it beats
            // the FocusZone. Otherwise it opens the buzz menu at the buzz point, anchoring it to the most recently
            // read word when the mic is tracking and the user isn't picking a word with the mouse.
            if (!appState.uiState.typeBuzzIndexMode) {
                TossupQuestionController.openBuzzMenuAtBuzzPoint(appState);
            }

            event.preventDefault();
            event.stopPropagation();
            break;

        case "N":
            if (appState.uiState.cycleIndex + 1 < appState.game.playableCycles.length) {
                appState.uiState.nextCycle();
            }
            event.preventDefault();
            event.stopPropagation();

            break;

        case "P":
            appState.uiState.previousCycle();
            event.preventDefault();
            event.stopPropagation();
            break;

        case "1":
        case "2":
        case "3":
        case "4":
        case "5":
            // This shortcut is only supported when bouncebacks are disabled. We could add support for it later and just
            // toggle through all the fields, but the logic is slightly more complicated and very few formats use
            // bouncebacks.
            if (appState.game.gameFormat.bonusesBounceBack) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            // If there are bonuses and they are active, toggle the bonus part. We have to do some defensive checks to
            // make sure that we can update the bonus
            const cycleIndex: number = appState.uiState.cycleIndex;
            const cycle: Cycle = appState.game.cycles[cycleIndex];
            const bonus: Bonus | undefined = appState.game.getBonus(cycleIndex);
            if (cycle.correctBuzz == undefined || bonus == undefined) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            // We know event.key is a number here, so we don't need to check for NaN
            const partIndex: number = Number(event.key) - 1;
            if (bonus.parts.length <= partIndex) {
                event.preventDefault();
                event.stopPropagation();

                return;
            }

            const teamName: string = cycle.correctBuzz.marker.player.teamName;
            const currentPoints: number | undefined = cycle.bonusAnswer?.parts[partIndex].points ?? 0;

            cycle.setBonusPartAnswer(partIndex, teamName, currentPoints > 0 ? 0 : bonus.parts[partIndex].value);

            event.preventDefault();
            event.stopPropagation();
            break;
        default:
            break;
    }
}

function update(appState: AppState, props: IModaqControlProps): void {
    if (props.buildVersion !== appState.uiState.buildVersion) {
        appState.uiState.setBuildVersion(props.buildVersion);
    }

    if (props.googleClientId !== appState.uiState.sheetsState.clientId) {
        appState.uiState.sheetsState.setClientId(props.googleClientId);
    }

    if (props.yappServiceUrl !== appState.uiState.yappServiceUrl) {
        appState.uiState.setYappServiceUrl(props.yappServiceUrl);
    }

    if (props.gameFormat != undefined && props.gameFormat !== appState.game.gameFormat) {
        appState.game.setGameFormat(props.gameFormat);
    }

    if (props.customExport != appState.uiState.customExportOptions) {
        if (props.customExport == undefined) {
            appState.uiState.resetCustomExport();
            appState.setCustomExportInterval(undefined);
        } else {
            const updateInterval: boolean =
                props.customExport.customExportInterval !== appState.uiState.customExportOptions?.customExportInterval;

            appState.uiState.setCustomExport(props.customExport);
            if (updateInterval) {
                appState.setCustomExportInterval(props.customExport.customExportInterval);
            }
        }
    }

    if (props.hideNewGame !== appState.uiState.hideNewGame) {
        appState.uiState.setHideNewGame(props.hideNewGame == true);
    }

    if (props.packetName !== appState.uiState.packetFilename && props.packetName !== appState.game.packet.name) {
        if (props.packetName != undefined) {
            appState.uiState.setPacketFilename(props.packetName);
            if (appState.game.packet) {
                appState.game.packet.setName(props.packetName);
            }
        } else {
            appState.uiState.resetPacketFilename();
        }
    }
}

interface IErrorBoundaryProps {
    appState: AppState;
}

interface IErrorBoundaryState {
    error: Error | string | undefined;
    showClearPrompt: boolean;
}

class ErrorBoundary extends React.Component<IErrorBoundaryProps, IErrorBoundaryState> {
    private static readonly dialogContent: IDialogContentProps = {
        type: DialogType.normal,
        title: "Reset",
        closeButtonAriaLabel: "Close",
        subText: "Do you wish to reset the reader? You will lose your current game.",
    };

    private static readonly exportButtonStyle: IButtonStyles = {
        root: {
            marginRight: 20,
            marginTop: 20,
        },
    };

    constructor(props: IErrorBoundaryProps) {
        super(props);

        this.state = { error: undefined, showClearPrompt: false };
    }

    static getDerivedStateFromError(error: Error | string): IErrorBoundaryState {
        // Update state so the next render will show the fallback UI.
        return { error, showClearPrompt: false };
    }

    // // componentDidCatch(error, errorInfo) {
    // //     // You can also log the error to an error reporting service. We don't have a logging service for this
    // // }

    public render() {
        if (this.state.error) {
            const text: string = "Error: " + this.state.error;

            // This shouldn't re-render often, and the user should leave the page soon when this appears, so skip
            // memoization
            const onClear = (): void => {
                const trunk = new AsyncTrunk(this.props.appState, { storage: localStorage, delay: 100 });
                trunk.clear();
                location.reload();
            };

            const hideDialog = (): void => {
                this.setState({ showClearPrompt: false });
            };

            const showDialog = (): void => {
                this.setState({ showClearPrompt: true });
            };

            const gameJson: Blob = new Blob([JSON.stringify(this.props.appState.game, null, 2)], {
                type: "application/json",
            });
            const url = URL.createObjectURL(gameJson);

            return (
                <Stack>
                    <StackItem>
                        <h2>Something went wrong</h2>
                    </StackItem>
                    <StackItem>
                        <Label>{text}</Label>
                    </StackItem>
                    <StackItem>
                        <Label>
                            Refreshing the page fixes most errors. If you keep seeing errors, click on the first button
                            to copy the JSON of all the events, then click on the second button to reset the app.
                        </Label>
                    </StackItem>
                    <StackItem>
                        <PrimaryButton
                            aria-label="Export game (JSON)"
                            text="Export game (JSON)"
                            styles={ErrorBoundary.exportButtonStyle}
                            href={url}
                            download="QuizBowlReader_Game_Error.json"
                        />
                        <DefaultButton onClick={showDialog} text="Reset" />
                    </StackItem>
                    <Dialog
                        hidden={!this.state.showClearPrompt}
                        onDismiss={hideDialog}
                        dialogContentProps={ErrorBoundary.dialogContent}
                    >
                        <DialogFooter>
                            <PrimaryButton onClick={onClear} text="OK" />
                            <DefaultButton onClick={hideDialog} text="Cancel" />
                        </DialogFooter>
                    </Dialog>
                </Stack>
            );
        }

        return this.props.children;
    }
}

export default ModaqControl;
