export const enum ModalVisibilityStatus {
    None,
    AddPlayer,
    AddQuestions,
    BonusProtest,
    CustomizeGameFormat,
    ExportToJson,
    ExportToSheets,
    Font,
    Help,
    ImportGame,
    Message,
    NewGame,
    RenamePlayer,
    ReorderPlayers,
    Scoresheet,
    TossupProtest,
}
